### ISSUE TITLE
Binary Candidates not Considered

### ISSUE THREAD

**Issue by SamuelAppleby** [datagram-db/knobab#46]
The current FPGrowth mining algorithm associates sets of activity id to the number of times they occur. Binary candidates are only added if the 2 activity labels occur in the same number of traces. Therefore a slight variation in the occurrence of one will mean binary patterns for these are never mined.

**Comment by jackbergus** [comment]
No, that is 1) Correct 2) Otherwise you cannot guarantee non-zero confidence and non-vacuity with at least one activation 3) Different support measures will also return patterns not existing across all traces, but which might be with declarative support greater than one. This is intended behaviour for optimization. Easy fixable by considering non 100% support.

**Comment by jackbergus** [comment]
-s 0.001 -b -t "/home/giacomo/testing.txt" -q 1

_testing.txt_
```
A	B
A	B
A	B
A	B
A	B
B
C
D
```

Result still contains a ChainSuccession:

```
Clause: ExclChoice(C, true, D, true )
	 - Pattern Maching Support: 0
	 - Declarative Pattern's Support: 0.25


Clause: ExclChoice(B, true, D, true )
	 - Pattern Maching Support: 0
	 - Declarative Pattern's Support: 0.875


Clause: ExclChoice(B, true, C, true )
	 - Pattern Maching Support: 0
	 - Declarative Pattern's Support: 0.875


Clause: ExclChoice(A, true, D, true )
	 - Pattern Maching Support: 0
	 - Declarative Pattern's Support: 0.75


Clause: ExclChoice(A, true, C, true )
	 - Pattern Maching Support: 0
	 - Declarative Pattern's Support: 0.75


Clause: ChainSuccession(A, true, B, true )
	 - Pattern Maching Support: 0.625
	 - Declarative Pattern's Support: 1
```
